---
output: 
html_document:
  number_sections=TRUE
pagetitle: Research
---

<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

## [HOME](https://joscif.github.io/) | [ABOUT ME]() | [ZAHN DATA COURSE](http://gzahn.github.io/data-course/) |

<div style= "float:right;position: relative;top:10px">
```{r, out.width = "300px",echo=FALSE}

```
</div>

<style>
div.gray { background-color:#1D741B; border-radius: 5px; padding: 20px;}
</style>
<div class = "gray">


# **Research**{#top}
Utah Valley University 



## Quick links:

####  [GITHUB REPO](https://github.com/Joscif/Data_Course_RAIGNE)
#### [Shared Course Notes](https://docs.google.com/document/d/1Nnjv1RkdegUR3pOp8Jb81ryE-_C59T4dLWYyJqVSz9Y/edit?usp=sharing)
(Anyone with link can edit)


___

Data Work

[Exam 3](http://joscif.github.io/Exam_3_rmd_web.html)    |    [Oryza Sativa Proj.](#Week-5)    |   




</div>

___

<style>
div.blue { background-color:#a89d82; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">

<div style= "float:right;position: relative;top:10px">
```{r, out.width = "250px",echo=FALSE}

```
</div>

